# Algorithm specific parameters for SAC
# Can be merged with a main environment config

training:
  device: "cuda:3"
  seed: 24
  nb_envs: 6
  timesteps: 5000000
  save_freq: 500000
  log_dir: "log"
  log_freq: 1000
  resume_path: "log/AUVTracking3D_v0/LQR/SAC/08-21_19/best_model.zip"

policy:
  net_arch:
    pi: [512, 256, 256]
    qf: [512, 256]

policy_hparams:
  policy: "SAC"
  lr: 0.0002
  buffer_size: 500000
  batch_size: 256
  gamma: 0.99
  tau: 0.005
  noise_std: 0.12
  start_timesteps: 50000
  
  # SAC specific
  auto_alpha: true
  alpha: 0.2
  alpha_lr: 0.0003

  # Collect settings
  step_per_collect: 5
  update_per_step: 0.2
  n_step: 2
