# Algorithm specific parameters for SAC
# Can be merged with a main environment config

training:
  device: "cuda:1"
  seed: 41
  nb_envs: 5
  timesteps: 2000000
  save_freq: 200000
  log_dir: "log"
  log_freq: 1000
  resume_path: "log/AUVTracking3D_v0_test/PID/SAC/09-12_20/rl_model_400000_steps.zip"

policy:
  net_arch:
    pi: [256, 256, 256]
    qf: [256, 256]

policy_hparams:
  policy: "SAC"
  lr: 0.0002
  buffer_size: 500000
  batch_size: 256
  gamma: 0.99
  tau: 0.005
  noise_std: 0.12
  start_timesteps: 50000
  
  # SAC specific
  auto_alpha: true
  alpha: 0.2
  alpha_lr: 0.0003

  replay_buffer:
    type: "ReplayBuffer"  # Options: "ReplayBuffer", "HerReplayBuffer"
    # HER specific parameters (only used if type is "HerReplayBuffer")
    her_kwargs:
      n_sampled_goal: 4  # 每个真实转换生成多少个虚拟转换
      goal_selection_strategy: "future"  # 目标选择策略: "future", "final", "episode", "random"

  # Collect settings
  step_per_collect: 5
  update_per_step: 0.2
  n_step: 2
