# Algorithm specific parameters for SAC
# Can be merged with a main environment config

training:
  device: "cuda:3"
  seed: 41
  nb_envs: 5
  timesteps: 3000000
  save_freq: 500000
  log_dir: "log"
  log_freq: 1000
  resume_path: "log/teacher/SAC/01-13_12/rl_model_1240000_steps.zip"

policy:
  net_arch:
    pi: [256, 256, 256]
    qf: [256, 256]

policy_hparams:
  policy: "SAC"
  lr: 0.0003
  buffer_size: 200000
  batch_size: 512
  gamma: 0.99
  tau: 0.005
  noise_std: 0.12
  start_timesteps: 30000
  
  # SAC specific
  auto_alpha: true
  alpha: 0.2
  alpha_lr: 0.0003

  # Collect settings
  step_per_collect: 5
  update_per_step: 0.2
  n_step: 2
