version: v0
name: AUVTracking3D_v0
render: false # print
draw_traj: false
eval_fixed: True
eval_fixed_pos: [[484, 257, -291, 0], [486, 257,-291,0]]
map: 'OpenWater-Bluerov2_RGB'
debug: false
t_steps: 1000

env:
  task_random: false
  insight: [true, [true, false]]
  noblock: true
  control_period: 0.2
  margin: 0.5
  margin2wall: 1.0
  num_targets: 1

scenario:
  size: [500, 500, 50]
  bottom_corner: [200, 0, -300]
  fix_depth: [5, 15]

agent:
  controller: 'LQR' # LQR , KEYBOARD
  controller_config:
    LQR:
      action_dim: 4
      control_frequency: 4
      random_lp: false
      l_p: [200, [10, 20, 30, 50, 75, 100, 200]]
      l_v: 0.01
      l_r: [0.01, 0.01, 0.05]
      r_f: 0.02
      r_t: 0.5
    PID:
      action_dim: 3
      control_frequency: 10
    KEYBOARD:
      action_dim: 3
      control_frequency: 10
  random: false
  use_sonar: false
  grid:
    use_grid: false
    p_prior: 0.5
    p_occ: 0.8
    p_free: 0.25
    resolution: 0.1
  sensor_r: 4.0
  fov: 100
  h_fov: 40
  sensor_r_sd: 0.2
  sensor_b_sd: 0.01
  sensor_e_sd: 0.01

target:
  target_dim: 6 # 3D target state: [x, y, z, vx, vy, vz]
  random: false
  const_q: [0.5, [0.01, 0.02, 0.05, 0.1, 0.4, 0.5, 0.8, 1.0, 1.5, 2.0, 3.0, 5.0, 10.0]]
  controller: 'Auto'
  controller_config:
    LQR:
      random_lp: false
      l_p: [10, [10, 20, 30, 50, 75, 100, 200]]
      l_v: 0.01
      l_r: [0.01, 0.01, 0.005]
      r_f: 0.15
      r_t: 1.5
    Manual:
      force: 10
    Auto:
      random_lp: false
      l_p: [10, [10, 20, 30, 50, 75, 100, 200]]
      l_v: 0.01
      l_r: [0.01, 0.01, 0.005]
      r_f: 0.15
      r_t: 1.5
  measurement_disfactor: 0.9
  target_init_cov: 50.0
  lin_dist_range_a2t: [1.0, 4.0]
  ang_dist_range_a2t: [-3.14159/5, 3.14159/5]
  lin_dist_range_t2b: [0.0, 2.0]
  ang_dist_range_t2b: [-3.14159/2, 3.14159/2]

is_training: true
algorithms: 'PPO'
policy: 'CNN'

# action is defined by the controller
action_range_high: [[1, 1, 1, 1], [1, 1, 1]]
action_range_low: [[0, -1, -1, -1], [0, -1, -1]]
action_range_scale: [[0.5, 3.14159/2, 0.3, 3.14159/20], [1.0, 0.3, 0.3]]

reward_param:
  c_mean: 0.2
  c_std: 0.0
  c_penalty: 5.0
  k_3: 0.0
  k_4: 0.0
  k_5: 0.0
